---
swagger: "2.0"
info:
  description: "API responsible for abstract payment gateways with simple endpoints"
  version: "1.0.0"
  title: "ProxyPay API"
host: "proxypay.github.io"
basePath: "/v1/"
schemes:
- "https"
- "http"
paths:
  /transaction:
    post:
      summary: "Creates a new transaction"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "transactionCreation"
        schema:
          $ref: "#/definitions/TransactionCreation"
      responses:
        200:
          description: "successful operation"
definitions:
  TransactionCreation:
    type: "object"
    required:
    - "reference"
    - "amount"
    - "cardNumber"
    - "expirationMonth"
    - "expirationYear"
    properties:
      capture:
        type: "boolean"
        description: "Flag to capture amount (`true`) or just Authorize (`false`): **Default:** `false`"
      reference:
        type: "string"
        description: "Used to identify transaction (line store order number). **Length <= 16**"
      amount:
        type: "integer"
        description: "Amount in cents, with no separation. E.g.: R$ 0,50 => `50` or R$ 1000,50 => `100050`). Value >= 1"
      installments:
        type: "integer"
        description: "Installments number. **Value >= 1 and <= 255. Default: 1**"
      cardNumber:
        type: "string"
        description: "Card number, only numbers. E.g.: for a card number *5555.5555.5555.4444* you should use `5555555555554444`"
      expirationMonth:
        type: "integer"
        description: "Card expiration month, only numbers. Value between 1 and 12"
      expirationYear:
        type: "integer"
        description: "Card expiration year, only numbers. Format *9999*, E.g: `2028`"
      cardHolderName:
        type: "string"
        description: "Card holder name, E.g.: `JOHN DOE`"
      securityCode:
        type: "string"
        description: "Security code, format *999*, E.g.: `123`"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
